name: Molecule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          path: "${{ github.repository }}"

      - name: Checkout hcv-servers
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: "truestory1/hcv-servers"
          path: "hcv-servers"
          token: ${{ secrets.GH_PAT }}

      - name: Checkout hcv-config-01
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: "truestory1/hcv-config-01"
          path: "hcv-config-01"
          token: ${{ secrets.GH_PAT }}

      - name: Debug
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Current directory: $(pwd)"
          ls -la $GITHUB_WORKSPACE
          tree $GITHUB_WORKSPACE

      - name: Molecule
        uses: gofrolist/molecule-action@cc5ba090a8158c98dc631804ee2a849711dcd7a7 # v2
