name: Molecule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          path: "${{ github.repository }}"

      - name: Checkout hcv-servers
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          repository: "truestory1/hcv-servers"
          path: "hcv-servers"
          token: ${{ secrets.GH_PAT }}

      - name: Checkout hcv-config-01
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          repository: "truestory1/hcv-config-01"
          path: "hcv-config-01"
          token: ${{ secrets.GH_PAT }}

      - name: Debug
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Current directory: $(pwd)"
          ls -la $GITHUB_WORKSPACE
          tree $GITHUB_WORKSPACE

      - name: Molecule
        uses: gofrolist/molecule-action@bcca93df83005c04285bd27e8e510608c9f3808f # v2
