name: Molecule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          path: "${{ github.repository }}"

      - name: Checkout hcv-servers
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          repository: "truestory1/hcv-servers"
          path: "hcv-servers"
          token: ${{ secrets.GH_PAT }}

      - name: Checkout hcv-config-01
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          repository: "truestory1/hcv-config-01"
          path: "hcv-config-01"
          token: ${{ secrets.GH_PAT }}

      - name: Debug
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Current directory: $(pwd)"
          ls -la $GITHUB_WORKSPACE
          tree $GITHUB_WORKSPACE

      - name: Molecule
        uses: gofrolist/molecule-action@c2d00c8a2e15124be14507f007473e96ba913d19 # v2
